spring:
    application:
        name: kafka-demo

    kafka:
        producer:
            bootstrap-servers:  localhost:9092
            key-deserializer:   org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

demo-app:
    topic: simple